name: CD - Deploy ML Model

# Trigger on pushes to main (or master)
on:
  push:
    branches:
      - main  # Change to 'master' if your branch is master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      # If using S3 for DVC, store these as GitHub Secrets
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dvc[s3]  # Adjust if you use a different DVC remote
        pip install -r requirements.txt

    - name: Pull DVC data
      run: |
        dvc pull

    - name: Train model
      run: |
        dvc repro

    - name: Push model to DVC remote
      run: |
        dvc push

    - name: Build Docker image
      run: |
        docker build -t knn-api:latest .

    - name: Run Docker container
      run: |
        docker run -d --rm -p 8000:8000 knn-api:latest

    - name: Test FastAPI API
      run: |
        sleep 10  # wait for container to start
        curl -s http://localhost:8000/docs | grep "Swagger"  # simple check
