name: CD - Deploy ML Model

on:
  push:
    branches:
      - master
  workflow_dispatch:   # Allows manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dvc[s3]
        pip install -r requirements.txt

    - name: Pull DVC data
      run: |
        dvc pull

    - name: Train model
      run: |
        dvc repro

    - name: Push model to DVC remote
      run: |
        dvc push

    - name: Build Docker image
      run: |
        docker build -t knn-api:latest .

    - name: Run Docker container
      run: |
        docker run -d -p 8000:8000 knn-api:latest
